# Generated by Django 2.0 on 2018-08-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bankaccount_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='username',
            new_name='account_type',
        ),
    ]
